import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { getTokenName } from './colorName'
import { needsColorSelector } from './colorSelector'

const outputDirectories = ['color', 'color-night']
const sourcesFile = 'sources.gni'

// Tokens are exported wholesale, so most of them go unreferenced in any given
// consumer. `tools:ignore="UnusedResources"` keeps Android lint quiet about
// that, matching what the `<color>` entries in `values*/colors.xml` do.
const selector = (color, alpha) => `<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="UnusedResources">
  <item android:color="${color}" android:alpha="${alpha}" />
</selector>
`

// A ColorStateList's filename is its resource name, so every composed color
// needs a file of its own. GN can't glob a directory and android_resources()
// requires every resource file to be listed, so a Chromium consumer would
// otherwise have to hand-maintain a copy of this list and keep it in step with
// each Nala bump. Emit it instead, from the same set that wrote the files.
const sourcesGni = (
  fileNames
) => `# Copyright (c) ${new Date().getFullYear()} The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by @brave/leo. Do not edit directly.
#
# Composed colors: tokens that apply an opacity to another token. Each is
# emitted as a ColorStateList, one file per resource, under both color/ and
# color-night/ -- the two directories always hold the same file names.
nala_composed_colors = [
${fileNames.map((fileName) => `  "${fileName}",`).join('\n')}
]
`

const clearOutputDirectories = (config) => {
  for (const directory of outputDirectories) {
    rmSync(path.join(config.buildPath, directory), {
      recursive: true,
      force: true
    })
  }
  rmSync(path.join(config.buildPath, sourcesFile), { force: true })
}

export default {
  do(dictionary, config) {
    clearOutputDirectories(config)

    const composedColors = dictionary.allTokens.filter(needsColorSelector)

    for (const token of composedColors) {
      const directory = token.path.includes('dark') ? 'color-night' : 'color'
      mkdirSync(path.join(config.buildPath, directory), { recursive: true })

      writeFileSync(
        path.join(config.buildPath, directory, `${token.name}.xml`),
        selector(
          `@color/${getTokenName(token.referencedVariable)}`,
          token.opacity
        )
      )
    }

    // `color/` and `color-night/` hold the same names, so dedupe across themes.
    const fileNames = [
      ...new Set(composedColors.map((token) => `${token.name}.xml`))
    ].sort()

    writeFileSync(
      path.join(config.buildPath, sourcesFile),
      sourcesGni(fileNames)
    )
  },

  undo(dictionary, config) {
    clearOutputDirectories(config)
  }
}
