name: Audit Dependencies
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        id: setup-node
        with:
          node-version: '24.11.1'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
        run: pnpm run audit_deps
